export enum ActionType {
  UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE',
  SHOW_ALERT = 'SHOW_ALERT',
  CLEAR_ALERT = 'CLEAR_ALERT',
  TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE',
  CHOOSE_USER_PLAYER = 'CHOOSE_USER_PLAYER',
  SELECT_COURSE = 'SELECT_COURSE'
}
