export enum SeasonActionType {
  CHANGE_ROUND_DETAILS_MODE = 'CHANGE_ROUND_DETAILS_MODE',
  TOGGLE_COURSE = 'TOGGLE_COURSE',
  VIEW_COURSE = 'VIEW_COURSE',
  TOGGLE_SCORE_TRACKER = 'TOGGLE_SCORE_TRACKER',
  VIEW_SCORECARD = 'VIEW_SCORECARD',
  TOGGLE_SCORECARD_NINE = 'TOGGLE_SCORECARD_NINE',
  VIEW_FRONT_NINE = 'VIEW_FRONT_NINE'
}
