export enum SeasonActionType {
  CHANGE_ROUND_DETAILS_MODE = 'CHANGE_ROUND_DETAILS_MODE',
  TOGGLE_COURSE = 'TOGGLE_COURSE',
  TOGGLE_SCORE_TRACKER = 'TOGGLE_SCORE_TRACKER',
  TOGGLE_SCORECARD_NINE = 'TOGGLE_SCORECARD_NINE'
}
